version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: ack
    volumes:
      - /app/mongo:/data/db
    restart: unless-stopped
    networks:
      - app-network
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.5'
    #       memory: 12G
    #     reservations:
    #       cpus: '1'
    #       memory: 6G
networks:
  app-network:
    name: app-network
    driver: bridge