version: '3.8'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: mongo1
    volumes:
      - /app/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 6G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 4G
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: mongo2
    volumes:
      - /app/mongors/data2:/data/db
    networks:
      - mongors-network
    ports:
      - 27022:27017
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 3G
    #     reservations:
    #       cpus: '0.25'
    #       memory: 1G
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    image: mongo:latest
    container_name: mongo3
    hostname: mongo3
    volumes:
      - /app/mongors/data3:/data/db
    networks:
      - mongors-network
    ports:
      - 27023:27017
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 3G
    #     reservations:
    #       cpus: '0.25'
    #       memory: 1G
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
networks:
  mongors-network:
    driver: bridge